import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';
import ContextProvider from '@/context/AuthContextProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ContextProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />

            <main className="flex-1 bg-zinc-50 font-sans dark:bg-black">
              {children}
            </main>

            <Footer />
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
